timeout: 300s
#options:
# machineType: 'N1_HIGHCPU_8'
# It's handy to later browse the logs trying to learn if an error is common to all runs of a language.
tags: ['golang', 'http', 'plugin']

steps:
# 'gofmt' only cares for the format, and doesn't touch any dependencies.
# It's a nice gatekeeper before any downloads, and to date any recent Go version will do.
- name: 'gcr.io/cloud-builders/go:debian'
  id: 'gofmt'
  entrypoint: 'bash'
  args: ['-c', 'diff <(echo -n) <(gofmt -s -d $(find . -type f -name "*.go" -not -path "./_*"))']

# Usually you'd go about this differently, for instance in hooks:
#   gofiles=$(git diff --cached --name-only --diff-filter=ACM "${origin}/master" | grep '\.go$')
#   gofmt -l $gofiles

# These two don't use dependencies. If any fails we can skip downloads.
# Indeed, 'golint' has the bad habit of checking anything in vendor/, so it's better to run this now before any deps appear.
- name: 'gcr.io/blitznote/golang/ineffassign'
  id: 'ineffassign'
  waitFor: ['gofmt']
  args: ['.']
- name: 'gcr.io/blitznote/golang/golint'
  id: 'lint'
  waitFor: ['gofmt']

# It's always good to cache dependencies for network connections and third-party services can be subject to interruptions and outages.
- name: 'gcr.io/cloud-builders/gsutil'
  waitFor: ['gofmt', 'ineffassign', 'lint']
  volumes:
  - name: 'third-party-sources'
    path: '/var/go/theirs'
  id: 'get cache'
  entrypoint: 'bash'
  args:
  - -c
  - |
    rm -f go.sum *caddyserver*.go;
    export RELEASE="$$(date --utc +'%Y-Q3')";
    if gsutil cp gs://cache_cloudbuild/http.upload/dependencies-$${RELEASE}.tar.xz ./; then
      tar -C /var/go/theirs/ -xaf "dependencies-$${RELEASE}.tar.xz" && rm "dependencies-$${RELEASE}.tar.xz";
    else
      exit 0;
    fi

# Now get any remaining dependencies of this plugin.
- &use_go
  name: 'gcr.io/cloud-builders/go:debian'
  volumes:
  - name: 'third-party-sources'
    path: '/var/go/theirs'
  env: ['GOPATH=/var/go/theirs:/go:/usr/share/gocode', 'GO111MODULE=on']
  id: 'get dependencies'
  args: ['mod', 'download']

# Now come steps (in Gitlab this were one stage actually) common to most projects written in Golang.
- <<: *use_go
  id: 'vet'
  waitFor: ['get dependencies']
  env: ['GOPATH=/var/go/theirs:/go:/usr/share/gocode', 'GO111MODULE=on', 'GOPROXY=off']
  args: ['vet', './...']
- <<: *use_go
  id: 'unittests'
  waitFor: ['get dependencies']
  env: ['GOPATH=/var/go/theirs:/go:/usr/share/gocode', 'GO111MODULE=on', 'GOPROXY=off']
  args: ['test', '-v', './...']

- &build_go
  <<: *use_go
  waitFor: ['get dependencies', 'vet', 'unittests']
  id: 'build linux amd64, Go current'
  env: ['GOPATH=/var/go/theirs:/go:/usr/share/gocode', 'GO111MODULE=on', 'GOARCH=amd64', 'GOOS=linux', 'GOPROXY=off']
  entrypoint: 'bash'
  args:
  - -c
  - |
    pwd;
    find -name 'go.mod' -type f;
    go env;
    go version;

    set -euo pipefail;
    D="$(mktemp -d)"
    <example.go sed \
      -e '/build ignore/{N;d}' \
      -e 's@"/"@"/web/path"@;s@:9000@:8000@' \
      -e '/http.Handle/a\\thttp.Handle(scope+"/", uploadHandler)' \
    >$$D/example.go;
    cd $$D/;
    printf 'module main\nrequire blitznote.com/src/http.upload/v3 v3.0.0\nreplace blitznote.com/src/http.upload/v3 => /workspace\n' >go.mod;

    go build \
      -ldflags  "-s -w -buildid ''" \
      -o /workspace/http.upload~$${GOARCH}_$${GOOS} \
      example.go;
    sed -i \
      -e '/cfg\./a\\tcfg.RandomizedSuffixLength = 4' \
      example.go;
    go build \
      -ldflags  "-s -w -buildid ''" \
      -o /workspace/http.upload.randsuffix4~$${GOARCH}_$${GOOS} \
      example.go;

#- <<: *build_go
#  id: 'build_windows_amd64'
#  env: ['GOPATH=/var/go/theirs:/go:/usr/share/gocode', 'GO111MODULE=on', 'GOARCH=amd64', 'GOOS=windows']

# Now come integration tests.
- name: 'gcr.io/cloud-builders/curl'
  waitFor: ['build linux amd64, Go current']
  id: 'integration test, example from doc'
  entrypoint: 'bash'
  args:
  - -c
  - |
    : $${TMPDIR:="/tmp"}
    set -eux;
    /workspace/http.upload~amd64_linux & sleep 0.2;

    curl -sfS -T /etc/os-release http://localhost:8000/web/path/from-release && test -s $${TMPDIR}/from-release;
    curl -sfS -F hostname=@/etc/hostname -F resolv.txt=@/etc/resolv.conf http://localhost:8000/web/path/;
    cmp -b /etc/hostname $${TMPDIR}/hostname;
    cmp -b /etc/resolv.conf $${TMPDIR}/resolv.conf;
    curl -sfS -X MOVE -H "Destination: /web/path/to-release" http://localhost:8000/web/path/from-release && test -s $${TMPDIR}/to-release;
    curl -sfS -vX DELETE http://localhost:8000/web/path/to-release;

    curl -sfS -T /etc/os-release http://localhost:8000/web/path/subdir/os-release && test -s $${TMPDIR}/subdir/os-release;
    rm -f $${TMPDIR}/subdir/os-release;
    rmdir $${TMPDIR}/subdir;

    kill %1

- name: 'gcr.io/cloud-builders/curl'
  waitFor: ['build linux amd64, Go current']
  id: 'integration test, image upload'
  entrypoint: 'bash'
  args:
  - -c
  - |
    : $${TMPDIR:="/tmp"}
    set -eux;
    /workspace/http.upload.randsuffix4~amd64_linux & sleep 0.2;

    truncate --size $[ 1*1024*1024 ] image1.jpg;
    curl -sfST image1.jpg http://localhost:8000/web/path/first-image.jpg;
    ls -1 $${TMPDIR}/*.jpg;
    test -s $${TMPDIR}/first-image_????.jpg;

    kill %1

# Do not uncomment this as Google Cloud Build for Github lacks the permissions to perform this step.
# Mark needs to issue the build separately, using a different account, for this to succeed.
#- name: 'docker.io/blitznote/debase:16.04'
#  waitFor: ['build linux amd64, Go current']
#  id: 'store dependencies'
#  volumes:
#  - name: 'third-party-sources'
#    path: '/var/go/theirs'
#  entrypoint: 'bash'
#  args:
#  - -c
#  - |
#    tar -C /var/go/theirs/ --sort=name \
#      --numeric-owner --owner=0 --group=0 \
#      --no-acls --no-selinux --no-xattrs \
#      --xz -cf "dependencies-$$(date --utc +'%Y-Q3').tar.xz" \
#        $$(ls -1 /var/go/theirs)

#artifacts:
#  objects:
#    location: 'gs://cache_cloudbuild/http.upload/'
#    paths: ['dependencies-*']
